Description of matRad_getEnvironment
matRad_getEnvironment
Purpose
matRad function to get the software environment matRad is running on
Synopsis
function [env, versionString] = matRad_getEnvironment()
Description
 matRad function to get the software environment matRad is running on
 call
   [env, versionString] = matRad_getEnvironment()
 input
   -
 output
   env:            outputs either 'MATLAB' or 'OCTAVE' as string
   versionString:  returns the version number as string
 References
   -
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 Copyright 2017 the matRad development team.
 This file is part of the matRad project. It is subject to the license
 terms in the LICENSE file found in the top-level directory of this
 distribution and at https://github.com/e0404/matRad/LICENSES.txt. No part
 of the matRad project, including this file, may be copied, modified,
 propagated, or distributed except according to the terms contained in the
 LICENSE file.
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Cross-reference information
This function calls:
This function is called by:
matRad_DicomExporter
matRad_exportDicomRTDoses matRad function to exportt resultGUI to dicom RT dose.
matRad_exportDicomRTStruct matRad function to export dicom RT structure set.
matRad_importDicom matRad wrapper function to import a predefined set of dicom files
matRad_example4_photonsMC % Example: Photon Treatment Plan using VMC++ dose calculation
matRad_example5_protons % Example: Proton Treatment Plan with subsequent Isocenter shift
matRadGUI matRad GUI
matRad_calcParticleDoseMC matRad MCsqaure monte carlo photon dose calculation wrapper
matRad_calcPhotonDose matRad photon dose calculation wrapper
matRad_interp1 interpolates 1-D data (table lookup) and utilizes griddedInterpolant
matRad_interp3 interpolates 3-D data (table lookup)
matRad_rc matRad rc script
matRad_showQualityIndicators matRad display of quality indicators as table
matRad_compileOmpMCInterface Compiles the ompMC interface (integrated as submodule)
matRad_DoseOptimizationFunction
matRad_OptimizerIPOPT
matRad_plotVoiContourSlice matRad function that plots the contours of the segmentations given in cst
matRad_checkMexFileExists Checks if a matching mex file exists, and can create a link
matRad_gammaIndex gamma index calculation
matRad_runTests % This file runs the complete matRad test suite.
Source code
function [env, versionString] = matRad_getEnvironment()
% matRad function to get the software environment matRad is running on
%
% call
%   [env, versionString] = matRad_getEnvironment()
%
% input
%   -
%
% output
%   env:            outputs either 'MATLAB' or 'OCTAVE' as string
%   versionString:  returns the version number as string
%
% References
%   -
%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Copyright 2017 the matRad development team.
%
% This file is part of the matRad project. It is subject to the license
% terms in the LICENSE file found in the top-level directory of this
% distribution and at https://github.com/e0404/matRad/LICENSES.txt. No part
% of the matRad project, including this file, may be copied, modified,
% propagated, or distributed except according to the terms contained in the
% LICENSE file.
%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% reduce runtime if function is called multiple times
matRad_cfg = MatRad_Config.instance();
env = matRad_cfg.env;
versionString = matRad_cfg.envVersion;
end
| Generated by m2html © 2005