% --- Creates and returns a handle to the GUI figure. 
function h1 = matRad_exportGUI_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end
load matRad_exportGUI.mat


appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'uipanel', 2, ...
    'text', 10, ...
    'uibuttongroup', 2, ...
    'radiobutton', 7, ...
    'pushbutton', 4, ...
    'edit', 4, ...
    'checkbox', 4, ...
    'listbox', 4, ...
    'popupmenu', 2, ...
    'uitable', 3), ...
    'override', 1, ...
    'release', [], ...
    'resize', 'none', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastFilename', 'C:\NiklasLocal\MATLAB\MatRad\IO\matRad_exportGUI.fig', ...
    'lastSavedFile', 'C:\NiklasLocal\MATLAB\MatRad\IO\matRad_exportGUI.m');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'PaperUnits','inches',...
'Units',get(0,'defaultfigureUnits'),...
'Position',[544 -7.5 357.5 512.5],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',[0.5 0.5 0.5],...
'CloseRequestFcn',get(0,'defaultfigureCloseRequestFcn'),...
'ResizeFcn',blanks(0),...
'IntegerHandle','off',...
'NextPlot',get(0,'defaultfigureNextPlot'),...
'Alphamap',get(0,'defaultfigureAlphamap'),...
'WindowButtonDownFcn',blanks(0),...
'WindowButtonUpFcn',blanks(0),...
'WindowButtonMotionFcn',blanks(0),...
'WindowScrollWheelFcn',blanks(0),...
'WindowKeyPressFcn',blanks(0),...
'WindowKeyReleaseFcn',blanks(0),...
'MenuBar','none',...
'ToolBar',get(0,'defaultfigureToolBar'),...
'Pointer',get(0,'defaultfigurePointer'),...
'PointerShapeHotSpot',get(0,'defaultfigurePointerShapeHotSpot'),...
'Name','Export Patient',...
'NumberTitle','off',...
'HandleVisibility','callback',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','figure1',...
'UserData',[],...
'WindowStyle',get(0,'defaultfigureWindowStyle'),...
'DockControls','off',...
'Resize',get(0,'defaultfigureResize'),...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'PaperSize',[8.5 11],...
'PaperType','usletter',...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'PaperOrientation',get(0,'defaultfigurePaperOrientation'),...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'btn_export';

h2 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'ListboxTop',0,...
'String','Export',...
'Position',[27 2.47435897435897 15.6 2.92307692307692],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)matRad_exportGUI('btn_export_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','btn_export',...
'UserData',[],...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'btn_cancel';

h3 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'ListboxTop',0,...
'String','Cancel',...
'Position',[46.8 2.47435897435897 15.8 2.92307692307692],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)matRad_exportGUI('btn_cancel_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)matRad_exportGUI('btn_cancel_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','btn_cancel',...
'UserData',[],...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'checkbox_CT';

h4 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','CT',...
'Style','checkbox',...
'Position',[2.6 32.3205128205128 15 1.76923076923077],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)matRad_exportGUI('checkbox_CT_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','checkbox_CT',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'checkbox_dose';

h5 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Result Cubes',...
'Style','checkbox',...
'Position',[2.4 20.8589743589744 17.6 1.76923076923077],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)matRad_exportGUI('checkbox_dose_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','checkbox_dose',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'label_dir_export';

h6 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Select export folder:',...
'Style','text',...
'Position',[2.6 36.1666666666667 36.6 1.07692307692309],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Children',[],...
'Tag','label_dir_export',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'pushbutton_dir_export_browse';

h7 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Browse',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[52.6 34.5512820512821 10.6 1.61538461538461],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)matRad_exportGUI('pushbutton_dir_export_browse_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton_dir_export_browse',...
'KeyPressFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'));

appdata = [];
appdata.lastValidTag = 'edit_dir_export';

h8 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String',blanks(0),...
'Style','edit',...
'Position',[2.6 34.5512820512821 47.2 1.61538461538461],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)matRad_exportGUI('edit_dir_export_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Enable',get(0,'defaultuicontrolEnable'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)matRad_exportGUI('edit_dir_export_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','edit_dir_export',...
'KeyPressFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'));

appdata = [];
appdata.lastValidTag = 'text_extension';

h9 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Extension',...
'Style','text',...
'Position',[2.4 9.78205128205128 60.2 1.38461538461538],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Children',[],...
'Tag','text_extension',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'popupmenu_extension';

h10 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',{  '*.nrrd'; '*.vtk'; '*.mha' },...
'Style','popupmenu',...
'Value',1,...
'Position',[2.6 8.24358974358974 60.2 1.53846153846154],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)matRad_exportGUI('popupmenu_extension_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)matRad_exportGUI('popupmenu_extension_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','popupmenu_extension');

appdata = [];
appdata.lastValidTag = 'uitable_vois';

h11 = uitable(...
'Parent',h1,...
'BackgroundColor',[1 1 1;0.941176470588235 0.941176470588235 0.941176470588235],...
'ColumnName',blanks(0),...
'ColumnWidth',{  20 278 },...
'Data',mat{1},...
'RowName',blanks(0),...
'Position',[14 316.5 300 106],...
'ColumnEditable',mat{2},...
'ColumnFormat',{  'logical' 'char' },...
'CellEditCallback',blanks(0),...
'CellSelectionCallback',blanks(0),...
'Children',[],...
'TooltipString',blanks(0),...
'Visible','off',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uitable_vois',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'uitable_doseCubes';

h12 = uitable(...
'Parent',h1,...
'BackgroundColor',[1 1 1;0.941176470588235 0.941176470588235 0.941176470588235],...
'ColumnName',blanks(0),...
'ColumnWidth',{  20 278 },...
'Data',mat{3},...
'RowName',blanks(0),...
'Position',[14 162.5 300 106],...
'ColumnEditable',mat{4},...
'ColumnFormat',{  'logical' 'char' },...
'CellEditCallback',blanks(0),...
'CellSelectionCallback',blanks(0),...
'Children',[],...
'TooltipString',blanks(0),...
'Visible','off',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uitable_doseCubes',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'checkbox_compress';

h13 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Compress',...
'Style','checkbox',...
'Value',1,...
'Position',[2.8 5.93589743589744 17.2 1.76923076923077],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)matRad_exportGUI('checkbox_compress_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','checkbox_compress',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


