% --- Creates and returns a handle to the GUI figure. 
function h1 = matRad_importGUI_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end

appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'text', 4, ...
    'edit', 5, ...
    'pushbutton', 8, ...
    'checkbox', 2), ...
    'override', 0, ...
    'release', [], ...
    'resize', 'none', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastSavedFile', 'C:\NiklasLocal\MATLAB\MatRad\IO\matRad_importGUI.m', ...
    'lastFilename', 'C:\NiklasLocal\MATLAB\MatRad\IO\matRad_importGUI.fig');
appdata.lastValidTag = 'figure_importDialog';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure_importDialog');

h1 = figure(...
'PaperUnits','inches',...
'Units','characters',...
'Position',[135.8 56.7692307692308 89.2 18.3846153846154],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',[0.5 0.5 0.5],...
'IntegerHandle','off',...
'MenuBar','none',...
'Name','Import Patient',...
'NumberTitle','off',...
'HandleVisibility','callback',...
'Tag','figure_importDialog',...
'WindowStyle','normal',...
'Resize',get(0,'defaultfigureResize'),...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'PaperSize',[8.5 11],...
'PaperType','usletter',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text2';

h2 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Patient CT file [HU]:',...
'Style','text',...
'Position',[1.8 16.4615384615385 32 1.07692307692308],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Children',[],...
'Tag','text2',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'edit_ctPath';

h3 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String',blanks(0),...
'Style','edit',...
'Position',[1.8 14.3846153846154 66.2 1.69230769230769],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)matRad_importGUI('edit_ctPath_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)matRad_importGUI('edit_ctPath_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','edit_ctPath');

appdata = [];
appdata.lastValidTag = 'pushbutton_ctPath';

h4 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Browse...',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[69.8 14.3846153846154 18.2 1.76923076923077],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)matRad_importGUI('pushbutton_ctPath_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','pushbutton_ctPath');

appdata = [];
appdata.lastValidTag = 'text_masks';

h5 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Binary Masks/Segmentations',...
'Style','text',...
'Position',[1.6 8.46153846153846 40.2 1.07692307692308],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Children',[],...
'Tag','text_masks',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'listbox_maskPaths';

h6 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'Max',2,...
'Min',get(0,'defaultuicontrolMin'),...
'String','',...
'Style','listbox',...
'Value',[],...
'Position',[1.8 3.38461538461539 66.2 4.69230769230769],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)matRad_importGUI('listbox_maskPaths_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)matRad_importGUI('listbox_maskPaths_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','listbox_maskPaths',...
'KeyPressFcn',@(hObject,eventdata)matRad_importGUI('listbox_maskPaths_KeyPressFcn',hObject,eventdata,guidata(hObject)));

appdata = [];
appdata.lastValidTag = 'pushbutton_addMaskPaths';

h7 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Add File(s)...',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[69.8 6.30769230769231 18.2 1.76923076923077],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)matRad_importGUI('pushbutton_addMaskPaths_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','pushbutton_addMaskPaths');

appdata = [];
appdata.lastValidTag = 'pushbutton_import';

h8 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Import',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[45.8 0.230769230769231 20.2 1.69230769230769],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)matRad_importGUI('pushbutton_import_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','pushbutton_import',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'pushbutton_cancel';

h9 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Cancel',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[67.8 0.230769230769231 20 1.69230769230769],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)matRad_importGUI('pushbutton_cancel_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','pushbutton_cancel',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'pushbutton_addMaskFolders';

h10 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Add Folder...',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[69.8 3.46153846153846 18.2 1.76923076923077],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)matRad_importGUI('pushbutton_addMaskFolders_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton_addMaskFolders',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'checkbox_huConvert';

h11 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Convert from HU?',...
'Style','checkbox',...
'Position',[2 12.5384615384615 23.2 1.76923076923077],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)matRad_importGUI('checkbox_huConvert_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tooltip','If this is checked, the import assumes that this is a CT given in HU and will convert with the given (or the default) HLUT',...
'TooltipString','If this is checked, the import assumes that this is a CT given in HU and will convert with the given (or the default) HLUT',...
'Tag','checkbox_huConvert',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'edit_hlut';

h12 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','matRad_default.hlut',...
'Style','edit',...
'Position',[1.8 10.6923076923077 66.2 1.69230769230769],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)matRad_importGUI('edit_hlut_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Enable','off',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)matRad_importGUI('edit_hlut_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','edit_hlut',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'pushbutton_hlutFile';

h13 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','HLUT file...',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[69.8 10.6923076923077 18.2 1.76923076923077],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)matRad_importGUI('pushbutton_hlutFile_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Enable','off',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton_hlutFile',...
'KeyPressFcn',blanks(0));


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


