Description of matRad_OptimizationProblem
matRad_OptimizationProblem
Purpose
Synopsis
This is a script file.
Description
Cross-reference information
This function calls:
matRad_constraintFunctions matRad IPOPT callback: constraint function for direct aperture optimization
matRad_constraintJacobian matRad IPOPT callback: jacobian function for direct aperture optimization
matRad_getConstraintBounds matRad IPOPT get constraint bounds function for direct aperture optimization
matRad_getJacobianStructure matRad IPOPT callback: get jacobian structure for direct aperture optimization
matRad_objectiveFunction matRad IPOPT callback: objective function for direct aperture optimization
matRad_objectiveGradient matRad IPOPT callback: gradient function for direct aperture optimization
matRad_OptimizationProblem
matRad_constraintFunctions matRad IPOPT callback: constraint function for inverse planning
matRad_constraintJacobian matRad IPOPT callback: jacobian function for inverse planning
matRad_getConstraintBounds matRad IPOPT get constraint bounds wrapper function
matRad_getJacobianStructure matRad IPOPT callback: jacobian structure function for inverse planning
matRad_objectiveFunction matRad IPOPT objective function wrapper
matRad_objectiveGradient matRad IPOPT callback: gradient function for inverse planning
This function is called by:
matRad_fluenceOptimization matRad inverse planning wrapper function
matRad_OptimizationProblemDAO
matRad_constraintFunctions matRad IPOPT callback: constraint function for direct aperture optimization
matRad_constraintJacobian matRad IPOPT callback: jacobian function for direct aperture optimization
matRad_getConstraintBounds matRad IPOPT get constraint bounds function for direct aperture optimization
matRad_getJacobianStructure matRad IPOPT callback: get jacobian structure for direct aperture optimization
matRad_objectiveFunction matRad IPOPT callback: objective function for direct aperture optimization
matRad_objectiveGradient matRad IPOPT callback: gradient function for direct aperture optimization
matRad_OptimizationProblem
Subfunctions
function obj = matRad_OptimizationProblem(backProjection)
function lb = lowerBounds(optiProb,w)
function ub = upperBounds(optiProb,w)
Source code
classdef matRad_OptimizationProblem < handle
    %matRad_OptimizationProblem Main Class for fluence optimization problems
    % Describes a standard fluence optimization problem by providing the
    % implementation of the objective & constraint function/gradient wrappers
    % and managing the mapping and backprojection of the respective dose-
    % related quantity
    %
    % References
    %   -
    %
    % %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %
    % Copyright 2020 the matRad development team.
    %
    % This file is part of the matRad project. It is subject to the license
    % terms in the LICENSE file found in the top-level directory of this
    % distribution and at https://github.com/e0404/matRad/LICENSES.txt. No part
    % of the matRad project, including this file, may be copied, modified,
    % propagated, or distributed except according to the terms contained in the
    % LICENSE file.
    %
    % %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    properties
        BP              %matRad_BackProjection object for mapping & backprojection
        bioOpt = '';
    end
    methods
        function obj = matRad_OptimizationProblem(backProjection)
            obj.BP = backProjection;
        end
        %Objective function declaration
        fVal = matRad_objectiveFunction(optiProb,w,dij,cst)
        %Objective gradient declaration
        fGrad = matRad_objectiveGradient(optiProb,w,dij,cst)
        %Constraint function declaration
        cVal = matRad_constraintFunctions(optiProb,w,dij,cst)
        %Constraint Jacobian declaration
        cJacob = matRad_constraintJacobian(optiProb,w,dij,cst)
        %Jacobian Structure
        jacobStruct = matRad_getJacobianStructure(optiProb,w,dij,cst)
        [cl,cu] = matRad_getConstraintBounds(optiProb,cst)
        function lb = lowerBounds(optiProb,w)
            lb = zeros(size(w));
        end
        function ub = upperBounds(optiProb,w)
            ub = Inf * ones(size(w));
        end
    end
end
| Generated by m2html © 2005