Description of matRad_interp3
matRad_interp3
Purpose
interpolates 3-D data (table lookup)
Synopsis
function y = matRad_interp3(xi,yi,zi,x,xq,yq,zq,mode,extrapVal)
Description
 interpolates 3-D data (table lookup)
 call
   y = matRad_interp3(xi,yi,zi,x,xq,yq,zy)
   y = matRad_interp3(xi,yi,zi,x,xq,yq,zy,mode)
   y = matRad_interp3(xi,yi,zi,x,xq,yq,zy,mode,extrapVal)
 input
   xi,yi,zi:   grid vectors
   x:          data
   xq,yq,zq:   coordinates of quer points as a grid
   mode:       optional interpolation mode (default linear)
   extrapVal:  (optional) value for extrapolation
 output
   y: interpolated data
   References
     -
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 Copyright 2019 the matRad development team.
 This file is part of the matRad project. It is subject to the license
 terms in the LICENSE file found in the top-level directory of this
 distribution and at https://github.com/e0404/matRad/LICENSES.txt. No part
 of the matRad project, including this file, may be copied, modified,
 propagated, or distributed except according to the terms contained in the
 LICENSE file.
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Cross-reference information
This function calls:
matRad_getEnvironment matRad function to get the software environment matRad is running on
This function is called by:
matRad_calcCubes matRad computation of all cubes for the resultGUI struct
matRad_calcDoseInit
matRad_calcParticleDoseMC matRad MCsqaure monte carlo photon dose calculation wrapper
matRad_calcPhotonDoseMC matRad ompMC monte carlo photon dose calculation wrapper
matRad_engelLeafSequencing multileaf collimator leaf sequencing algorithm
matRad_interpRadDepth down/up sampling the radiological depth dose cubes
matRad_resizeCstToGrid matRad function to resize the ct to a given resolution
matRad_siochiLeafSequencing multileaf collimator leaf sequencing algorithm
matRad_xiaLeafSequencing multileaf collimator leaf sequencing algorithm
Source code
function y = matRad_interp3(xi,yi,zi,x,xq,yq,zq,mode,extrapVal)
% interpolates 3-D data (table lookup)
%
% call
%   y = matRad_interp3(xi,yi,zi,x,xq,yq,zy)
%   y = matRad_interp3(xi,yi,zi,x,xq,yq,zy,mode)
%   y = matRad_interp3(xi,yi,zi,x,xq,yq,zy,mode,extrapVal)
%
% input
%   xi,yi,zi:   grid vectors
%   x:          data
%   xq,yq,zq:   coordinates of quer points as a grid
%   mode:       optional interpolation mode (default linear)
%   extrapVal:  (optional) value for extrapolation
%
% output
%   y: interpolated data
%
%   References
%     -
%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Copyright 2019 the matRad development team.
%
% This file is part of the matRad project. It is subject to the license
% terms in the LICENSE file found in the top-level directory of this
% distribution and at https://github.com/e0404/matRad/LICENSES.txt. No part
% of the matRad project, including this file, may be copied, modified,
% propagated, or distributed except according to the terms contained in the
% LICENSE file.
%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[env, ~] = matRad_getEnvironment();
if nargin < 8
    mode = 'linear';
end
if nargin < 9
    extrapVal = NaN;
end
switch env
    case 'MATLAB'
        y = interp3(xi,yi,zi,x,xq,yq,zq,mode,extrapVal);
    case 'OCTAVE'
        [xqMesh,yqMesh,zqMesh] = meshgrid(xq,yq,zq);
        y = interp3(xi,yi,zi,x,xqMesh,yqMesh,zqMesh,mode,extrapVal);
end
| Generated by m2html © 2005