Description of matRad_BackProjection
matRad_BackProjection
Purpose
Synopsis
This is a script file.
Description
Cross-reference information
This function calls:
matRad_BackProjection
This function is called by:
matRad_BackProjection
matRad_ConstantRBEProjection
matRad_DoseProjection
matRad_EffectProjection
Subfunctions
function obj = matRad_BackProjection()
function obj = compute(obj,dij,w)
function obj = computeGradient(obj,dij,doseGrad,w)
function d = GetResult(obj)
function wGrad = GetGradient(obj)
function d = computeResult(obj,dij,w)
function wGrad = projectGradient(obj,dij,doseGrad,w)
function d = computeSingleScenario(obj,dij,scen,w)
function wGrad = projectSingleScenarioGradient(obj,dij,doseGrad,scen,w)
Source code
classdef matRad_BackProjection
% matRad_BackProjection superclass for all backprojection algorithms
% used within matRad optimzation processes
%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Copyright 2019 the matRad development team.
%
% This file is part of the matRad project. It is subject to the license
% terms in the LICENSE file found in the top-level directory of this
% distribution and at https://github.com/e0404/matRad/LICENSES.txt. No part
% of the matRad project, including this file, may be copied, modified,
% propagated, or distributed except according to the terms contained in the
% LICENSE file.
%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    properties (Access = protected)
        wCache
        wGradCache  %different cache for optimal performance (if multiple evaluations of objective but not gradient are required)
        d
        wGrad
    end
    properties
        dij          %reference to matRad dij struct (to enable local changes)
    end
    methods
        function obj = matRad_BackProjection()
            obj.wCache = [];
            obj.wGradCache = [];
            obj.d = [];
            obj.wGrad = [];
        end
        function obj = compute(obj,dij,w)
            if ~isequal(obj.wCache,w)
                obj.d = obj.computeResult(dij,w);
                obj.wCache = w;
            end
        end
        function obj = computeGradient(obj,dij,doseGrad,w)
            if ~isequal(obj.wGradCache,w)
                obj.wGrad = obj.projectGradient(dij,doseGrad,w);
                obj.wGradCache = w;
            end
        end
        function d = GetResult(obj)
            d = obj.d;
        end
        function wGrad = GetGradient(obj)
            wGrad = obj.wGrad;
        end
        function d = computeResult(obj,dij,w)
            d = cell(size(dij.physicalDose));
            d = arrayfun(@(scen) computeSingleScenario(obj,dij,scen,w),ones(size(dij.physicalDose)),'UniformOutput',false);
        end
        function wGrad = projectGradient(obj,dij,doseGrad,w)
            wGrad = cell(size(dij.physicalDose));
            wGrad = arrayfun(@(scen) projectSingleScenarioGradient(obj,dij,doseGrad,scen,w),ones(size(dij.physicalDose)),'UniformOutput',false);
        end
    end
    %These should be abstract methods, however Octave can't parse them. As soon
    %as Octave is able to do this, they should be made abstract again
    methods %(Abstract)
        function d = computeSingleScenario(obj,dij,scen,w)
            error('Function needs to be implemented');
        end
        function wGrad = projectSingleScenarioGradient(obj,dij,doseGrad,scen,w)
            error('Function needs to be implemented');
        end
    end
end
| Generated by m2html © 2005