name: 'Matlab Test'
author: 'e0404'
description: 'Runs a Matlab Test for a given version'

inputs:
  matlab-version:
    description: Matlab Version, e.g. R2022b
    required: true

runs:
  using: 'composite'
  steps:       
    # Install MATLAB
    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ inputs.matlab-version }}
        products: Image_Processing_Toolbox Parallel_Computing_Toolbox Optimization_Toolbox

    # Runs test command
    - name: Run Tests
      uses: matlab-actions/run-command@v2
      with:
        command: matRad_runTests('test',true);
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-matlab-${{ inputs.matlab-version }}
        path: |
          testresults.xml
          coverage.xml
          coverage.json

    
    - name: Publish Test Results
      uses: test-summary/action@v2
      if: success() || failure()
      with:
        paths: testresults.xml
        # check_name: "${{ github.job }}"