% -------------------------------------------------------------------
%  Generated by MATLAB on 26-May-2017 12:24:04
%  MATLAB version: 9.0.0.341360 (R2016a)
% -------------------------------------------------------------------
saveVarsMat = load('finalfunc.mat');

final3 = saveVarsMat.final3; % <1x1 function_handle> unsupported class

clear saveVarsMat;
