figure
hold

% [ix,radialDist_sq] = matRad_calcGeoDists(rot_coordsV, ...
%                                                      stf(i).sourcePoint_bev, ...
%                                                      [-100,10000,30], ...
%                                                      machine.meta.SAD, ...
%                                                      radDepthIx, ...
%                                                      maxLateralCutoffDoseCalc);
                                                 
[ixx,ixy,ixz]=ind2sub([160 160 160],V(ix));
scatter3(ixx,ixy,ixz)
[ixx,ixy,ixz]=ind2sub([160 160 160],V(ix(currIx)));
scatter3(ixx,ixy,ixz,'r')


% [ix,radialDist_sq] = matRad_calcGeoDists(rot_coordsV, ...
%                                                      stf(i).sourcePoint_bev, ...
%                                                      [-70,10000,30], ...
%                                                      machine.meta.SAD, ...
%                                                      radDepthIx, ...
%                                                      maxLateralCutoffDoseCalc);
%                                                  
% [ixx,ixy,ixz]=ind2sub([160 160 160],V(ix));
% scatter3(ixx,ixy,ixz,'r')
% 
% [ix,radialDist_sq] = matRad_calcGeoDists(rot_coordsV, ...
%                                                      stf(i).sourcePoint_bev, ...
%                                                      [-100,10000,60], ...
%                                                      machine.meta.SAD, ...
%                                                      radDepthIx, ...
%                                                      maxLateralCutoffDoseCalc);
%                                                  
% [ixx,ixy,ixz]=ind2sub([160 160 160],V(ix));
% scatter3(ixx,ixy,ixz,'g')
% 
% [ix,radialDist_sq] = matRad_calcGeoDists(rot_coordsV, ...
%                                                      stf(i).sourcePoint_bev, ...
%                                                      [-100,12000,30], ...
%                                                      machine.meta.SAD, ...
%                                                      radDepthIx, ...
%                                                      maxLateralCutoffDoseCalc);
%                                                  
% [ixx,ixy,ixz]=ind2sub([160 160 160],V(ix));
% scatter3(ixx,ixy,ixz,'k')