name: Coverage Report

permissions:
    checks: write
    pull-requests: write
    actions: read
    contents: read
    

on:
    workflow_call:
            
jobs:
    coverage_report:
        runs-on: ubuntu-latest
            
        steps:
            
            - name: Download Coverage Artifact
              uses: actions/download-artifact@v4
              with:
                  name: test-results-matlab-R2022b
                  path: coverage

            - name: Upload to Coveralls
              uses: coverallsapp/github-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  file: coverage/coverage.json
                  format: coveralls
            
            - name: Publish Coverage Report
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                  filename: coverage/coverage.xml
                  badge: true
                  fail_below_min: false
                  format: markdown
                  hide_branch_rate: true
                  hide_complexity: true
                  indicators: true
                  output: both
                  thresholds: '40 70'

            - name: Attach Job Summary
              uses: actions/github-script@v7
              with:
                script: |
                  const fs = require('fs');
                  const markdownContent = fs.readFileSync('code-coverage-results.md', 'utf8');
                  core.summary.addRaw(markdownContent);
                  core.summary.write();
                        
            - name: Add Coverage PR Comment
              uses: marocchino/sticky-pull-request-comment@v2
              if: github.event_name == 'pull_request'
              with:
                  recreate: true
                  path: code-coverage-results.md
