name: Build Sphinx Documentation

on:
    push:
    pull_request:

jobs:
    build-docs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: '3.13'

            - name: Install sphinx and dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r docs/requirements.txt

            - name: Build documentation
              run: sphinx-build docs _doc

            - name: Upload artifacts
              uses: actions/upload-artifact@v6
              with:
                  name: documentation
                  path: _doc
